version: '3.9'

services:
  app:
    container_name: auth_service_app
    restart: always
    # command: bash -c "alembic upgrade head && uvicorn auth_service.main:app --reload --host 0.0.0.0 --port 8000"
    command: bash -c "alembic upgrade head && gunicorn -k uvicorn.workers.UvicornWorker auth_service.main:app --reload --bind 0.0.0.0:8000"
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .docker-env
    depends_on:
      - db

  db:
    image: postgres
    container_name: auth_service_db
    restart: always
    command: -p 5433
    expose:
      - 5433
    env_file:
      - .docker-env

  pgadmin:
    image: dpage/pgadmin4
    container_name: auth_service_pgadmin
    ports:
      - "5050:80"
    env_file:
      - .docker-env
    depends_on:
      - db
